#quiz homework

#imports:
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sys
import sqlite3

#global variables: 
currentUser = ''
style = ("color: white;\n"
        "border-width: 2px;\n"
        "border-style: solid;\n"
        "border-color: white;")

#all of the widnows, along with the coding of all the windows buttons and functions.:
class Ui_logOnWindow(object):
    def setupUi(self, logOnWindow):
        global style
        logOnWindow.setObjectName("logOnWindow")
        logOnWindow.resize(800, 501)
        logOnWindow.setMinimumSize(QtCore.QSize(800, 501))
        logOnWindow.setMaximumSize(QtCore.QSize(800, 501))
        logOnWindow.setStyleSheet("background: #282828;")
        self.centralwidget = QtWidgets.QWidget(logOnWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 0, 800, 91))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(40)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setStyleSheet("color: white;")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(False)
        self.title.setOpenExternalLinks(False)
        self.title.setObjectName("title")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(210, 120, 381, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.usernameTitle = QtWidgets.QLabel(self.verticalLayoutWidget)
        font.setPointSize(25)
        self.usernameTitle.setFont(font)
        self.usernameTitle.setStyleSheet("color: white;")
        self.usernameTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.usernameTitle.setObjectName("usernameTitle")
        self.verticalLayout.addWidget(self.usernameTitle)
        self.usernameEntry = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font.setPointSize(20)
        self.usernameEntry.setFont(font)
        self.usernameEntry.setStyleSheet(style)
        self.usernameEntry.setText("")
        self.usernameEntry.setFrame(False)
        self.usernameEntry.setAlignment(QtCore.Qt.AlignCenter)
        self.usernameEntry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.usernameEntry.setObjectName("usernameEntry")
        self.verticalLayout.addWidget(self.usernameEntry)
        self.passwordTitle = QtWidgets.QLabel(self.verticalLayoutWidget)
        font.setPointSize(25)
        self.passwordTitle.setFont(font)
        self.passwordTitle.setStyleSheet("color: white;")
        self.passwordTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordTitle.setObjectName("passwordTitle")
        self.verticalLayout.addWidget(self.passwordTitle)
        self.passwordEntry = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font.setPointSize(20)
        self.passwordEntry.setFont(font)
        self.passwordEntry.setStyleSheet(style)
        self.passwordEntry.setText("")
        self.passwordEntry.setFrame(True)
        self.passwordEntry.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.passwordEntry.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordEntry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.passwordEntry.setClearButtonEnabled(False)
        self.passwordEntry.setObjectName("passwordEntry")
        self.verticalLayout.addWidget(self.passwordEntry)
        self.createAccountButton = QtWidgets.QPushButton(self.centralwidget)
        self.createAccountButton.setGeometry(QtCore.QRect(610, 450, 181, 41))
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.createAccountButton.setFont(font)
        self.createAccountButton.setStyleSheet("color: white;")
        self.createAccountButton.setAutoDefault(False)
        self.createAccountButton.setDefault(False)
        self.createAccountButton.setFlat(False)
        self.createAccountButton.setObjectName("createAccountButton")
        self.logOnButton = QtWidgets.QPushButton(self.centralwidget)
        self.logOnButton.setGeometry(QtCore.QRect(210, 350, 381, 61))
        font.setPointSize(25)
        self.logOnButton.setFont(font)
        self.logOnButton.setStyleSheet("color: white;")
        self.logOnButton.setAutoDefault(False)
        self.logOnButton.setDefault(False)
        self.logOnButton.setFlat(False)
        self.logOnButton.setObjectName("logOnButton")
        logOnWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(logOnWindow)
        QtCore.QMetaObject.connectSlotsByName(logOnWindow)
        self.logOnButton.clicked.connect(self.logOn)
        self.createAccountButton.clicked.connect(self.createAccount)

    def retranslateUi(self, logOnWindow):
        _translate = QtCore.QCoreApplication.translate
        logOnWindow.setWindowTitle(_translate("logOnWindow", "MainWindow"))
        self.title.setText(_translate("logOnWindow", "Micheal\'s Quiz Homework"))
        self.usernameTitle.setText(_translate("logOnWindow", "Username:"))
        self.usernameEntry.setPlaceholderText(_translate("logOnWindow", "Enter Username Here"))
        self.passwordTitle.setText(_translate("logOnWindow", "Password:"))
        self.passwordEntry.setPlaceholderText(_translate("logOnWindow", "Enter Password Here"))
        self.createAccountButton.setText(_translate("logOnWindow", "Create Account"))
        self.logOnButton.setText(_translate("logOnWindow", "Log In"))

    def logOn(self):
        global currentUser
        username = self.usernameEntry.text()
        password = self.passwordEntry.text()
        fetchedData = databaseAccess('SELECT * FROM tblUsers')
        valid = False
        for records in fetchedData:
            if records[0] == username:
                if records[1] == password:
                    valid = True
        if valid == False:
            messageBox('Input Error!', 'Sorry either the username or password you entered was invalid')
        else:
            currentUser = user(username)
            QtWidgets.qApp.quit()
    
    def createAccount(self):
        global currentUser
        currentUser = 'createNew'
        QtWidgets.qApp.quit()
        
class Ui_CreateUserWindow(object):
    def setupUi(self, CreateUserWindow):
        global style
        CreateUserWindow.setObjectName("CreateUserWindow")
        CreateUserWindow.resize(800, 501)
        CreateUserWindow.setMinimumSize(QtCore.QSize(800, 501))
        CreateUserWindow.setMaximumSize(QtCore.QSize(800, 501))
        CreateUserWindow.setStyleSheet("background: #282828;")
        self.centralwidget = QtWidgets.QWidget(CreateUserWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 0, 800, 91))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(40)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setStyleSheet("color: white;")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(False)
        self.title.setOpenExternalLinks(False)
        self.title.setObjectName("title")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(210, 120, 381, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.usernameTitle = QtWidgets.QLabel(self.verticalLayoutWidget)
        font.setPointSize(25)
        self.usernameTitle.setFont(font)
        self.usernameTitle.setStyleSheet("color: white;")
        self.usernameTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.usernameTitle.setObjectName("usernameTitle")
        self.verticalLayout.addWidget(self.usernameTitle)
        self.usernameEntry = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font.setPointSize(20)
        self.usernameEntry.setFont(font)
        self.usernameEntry.setStyleSheet(style)
        self.usernameEntry.setText("")
        self.usernameEntry.setFrame(False)
        self.usernameEntry.setAlignment(QtCore.Qt.AlignCenter)
        self.usernameEntry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.usernameEntry.setObjectName("usernameEntry")
        self.verticalLayout.addWidget(self.usernameEntry)
        self.passwordTitle = QtWidgets.QLabel(self.verticalLayoutWidget)
        font.setPointSize(25)
        self.passwordTitle.setFont(font)
        self.passwordTitle.setStyleSheet("color: white;")
        self.passwordTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordTitle.setObjectName("passwordTitle")
        self.verticalLayout.addWidget(self.passwordTitle)
        self.passwordEntry = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font.setPointSize(20)
        self.passwordEntry.setFont(font)
        self.passwordEntry.setStyleSheet(style)
        self.passwordEntry.setText("")
        self.passwordEntry.setFrame(True)
        self.passwordEntry.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.passwordEntry.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordEntry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.passwordEntry.setClearButtonEnabled(False)
        self.passwordEntry.setObjectName("passwordEntry")
        self.verticalLayout.addWidget(self.passwordEntry)
        self.logOnButton = QtWidgets.QPushButton(self.centralwidget)
        self.logOnButton.setGeometry(QtCore.QRect(610, 450, 181, 41))
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.logOnButton.setFont(font)
        self.logOnButton.setStyleSheet("color: white;")
        self.logOnButton.setAutoDefault(False)
        self.logOnButton.setDefault(False)
        self.logOnButton.setFlat(False)
        self.logOnButton.setObjectName("logOnButton")
        self.createAccountButton = QtWidgets.QPushButton(self.centralwidget)
        self.createAccountButton.setGeometry(QtCore.QRect(210, 350, 381, 61))
        font.setPointSize(25)
        self.createAccountButton.setFont(font)
        self.createAccountButton.setStyleSheet("color: white;")
        self.createAccountButton.setAutoDefault(False)
        self.createAccountButton.setDefault(False)
        self.createAccountButton.setFlat(False)
        self.createAccountButton.setObjectName("createAccountButton")
        CreateUserWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(CreateUserWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateUserWindow)
        self.createAccountButton.clicked.connect(self.createAccount)
        self.logOnButton.clicked.connect(self.logOn)

    def retranslateUi(self, CreateUserWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateUserWindow.setWindowTitle(_translate("CreateUserWindow", "MainWindow"))
        self.title.setText(_translate("CreateUserWindow", "Micheal\'s Quiz Homework"))
        self.usernameTitle.setText(_translate("CreateUserWindow", "Username:"))
        self.usernameEntry.setPlaceholderText(_translate("CreateUserWindow", "Enter Username Here"))
        self.passwordTitle.setText(_translate("CreateUserWindow", "Password:"))
        self.passwordEntry.setPlaceholderText(_translate("CreateUserWindow", "Enter Password Here"))
        self.logOnButton.setText(_translate("CreateUserWindow", "Log In"))
        self.createAccountButton.setText(_translate("CreateUserWindow", "Create Account"))

    def logOn(self):
        QtWidgets.qApp.quit()

    def createAccount(self):
        username = self.usernameEntry.text()
        password = self.passwordEntry.text()
        fetchedData = databaseAccess('SELECT * FROM tblUsers')
        valid = True
        for records in fetchedData:
            if records[0] == username:
                valid = False
        if valid == False:
            messageBox('Input Error!', 'Sorry that username is taken')
        else:
            databaseAccess(('INSERT INTO tblUsers (Username, Password) VALUES(?, ?)'), (username, password))
            QtWidgets.qApp.quit()

class Ui_adminMainMenuWindow(object):
    def setupUi(self, adminMainMenuWindow):
        adminMainMenuWindow.setObjectName("adminMainMenuWindow")
        adminMainMenuWindow.resize(800, 361)
        adminMainMenuWindow.setMinimumSize(QtCore.QSize(800, 361))
        adminMainMenuWindow.setMaximumSize(QtCore.QSize(800, 361))
        adminMainMenuWindow.setStyleSheet("background: #282828;")
        self.centralwidget = QtWidgets.QWidget(adminMainMenuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 0, 800, 91))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(40)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setStyleSheet("color: white;")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(False)
        self.title.setOpenExternalLinks(False)
        self.title.setObjectName("title")
        self.quitButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitButton.setGeometry(QtCore.QRect(610, 310, 181, 41))
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.quitButton.setFont(font)
        self.quitButton.setStyleSheet("color: white;")
        self.quitButton.setAutoDefault(False)
        self.quitButton.setDefault(False)
        self.quitButton.setFlat(False)
        self.quitButton.setObjectName("quitButton")
        self.createQuiz = QtWidgets.QPushButton(self.centralwidget)
        self.createQuiz.setGeometry(QtCore.QRect(210, 240, 381, 61))
        font.setPointSize(25)
        self.createQuiz.setFont(font)
        self.createQuiz.setStyleSheet("color: white;")
        self.createQuiz.setAutoDefault(False)
        self.createQuiz.setDefault(False)
        self.createQuiz.setFlat(False)
        self.createQuiz.setObjectName("createQuiz")
        self.deleteComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.deleteComboBox.setGeometry(QtCore.QRect(360, 100, 241, 41))
        self.deleteComboBox.setObjectName("deleteComboBox")
        self.deleteQuizTitle = QtWidgets.QLabel(self.centralwidget)
        self.deleteQuizTitle.setGeometry(QtCore.QRect(0, 100, 351, 41))
        font.setPointSize(24)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.deleteQuizTitle.setFont(font)
        self.deleteQuizTitle.setStyleSheet("color: white;")
        self.deleteQuizTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.deleteQuizTitle.setWordWrap(False)
        self.deleteQuizTitle.setOpenExternalLinks(False)
        self.deleteQuizTitle.setObjectName("deleteQuizTitle")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(610, 100, 181, 41))
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.deleteButton.setFont(font)
        self.deleteButton.setStyleSheet("color: white;")
        self.deleteButton.setAutoDefault(False)
        self.deleteButton.setDefault(False)
        self.deleteButton.setFlat(False)
        self.deleteButton.setObjectName("deleteButton")
        self.EditQuizTitle = QtWidgets.QLabel(self.centralwidget)
        self.EditQuizTitle.setGeometry(QtCore.QRect(0, 150, 351, 41))
        font.setPointSize(24)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.EditQuizTitle.setFont(font)
        self.EditQuizTitle.setStyleSheet("color: white;")
        self.EditQuizTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.EditQuizTitle.setWordWrap(False)
        self.EditQuizTitle.setOpenExternalLinks(False)
        self.EditQuizTitle.setObjectName("EditQuizTitle")
        self.editComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.editComboBox.setGeometry(QtCore.QRect(360, 150, 241, 41))
        self.editComboBox.setObjectName("editComboBox")
        self.editButton = QtWidgets.QPushButton(self.centralwidget)
        self.editButton.setGeometry(QtCore.QRect(610, 150, 181, 41))
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.editButton.setFont(font)
        self.editButton.setStyleSheet("color: white;")
        self.editButton.setAutoDefault(False)
        self.editButton.setDefault(False)
        self.editButton.setFlat(False)
        self.editButton.setObjectName("editButton")
        quizzes = databaseAccess('SELECT QuizName FROM tblQuiz')
        for titles in quizzes:
            self.deleteComboBox.addItem(titles[0])
            self.editComboBox.addItem(titles[0])
        adminMainMenuWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(adminMainMenuWindow)
        QtCore.QMetaObject.connectSlotsByName(adminMainMenuWindow)
        self.createQuiz.clicked.connect(self.createQuizMethod)
        self.deleteButton.clicked.connect(self.deleteAQuizMethod)
        self.quitButton.clicked.connect(self.quitMethod)
        self.editButton.clicked.connect(self.editQuizMethod)

    def retranslateUi(self, adminMainMenuWindow):
        _translate = QtCore.QCoreApplication.translate
        adminMainMenuWindow.setWindowTitle(_translate("adminMainMenuWindow", "MainWindow"))
        self.title.setText(_translate("adminMainMenuWindow", "Admin Main Menu"))
        self.quitButton.setText(_translate("adminMainMenuWindow", "Quit"))
        self.createQuiz.setText(_translate("adminMainMenuWindow", "Create A New Quiz "))
        self.deleteQuizTitle.setText(_translate("adminMainMenuWindow", "Delete a Quiz:"))
        self.deleteButton.setText(_translate("adminMainMenuWindow", "Delete"))
        self.EditQuizTitle.setText(_translate("adminMainMenuWindow", "Edit A Qiuz:"))
        self.editButton.setText(_translate("adminMainMenuWindow", "Edit"))

    def quitMethod(self):
        global currentUser
        currentUser.method = 'quit'
        QtWidgets.qApp.quit()

    def createQuizMethod(self):
        global currentUser
        currentUser.method = 'createNewQuiz'
        QtWidgets.qApp.quit()

    def editQuizMethod(self):
        selected = self.editComboBox.currentText() 
        global currentUser
        if selected != '':
            currentUser.method = selected
            QtWidgets.qApp.quit()

    def deleteAQuizMethod(self):
        selected = self.deleteComboBox.currentText()
        msgBox = QMessageBox()
        msgBox.setIcon(QMessageBox.Warning)
        msgBox.setText(f'Warning, by pressing ok, the quiz titled {selected} will be permenantly deleted')
        msgBox.setWindowTitle('Permenant Deletion Warning')
        msgBox.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        answer = msgBox.exec()
        if answer == 1024:
            databaseAccess(('DELETE FROM tblQuiz WHERE QuizName = ?'), (selected,))
            index = self.deleteComboBox.findText(selected)
            self.editComboBox.removeItem(index)
            self.deleteComboBox.removeItem(index)
            messageBox('Successful deletion', f'The quiz titled {selected} has been successfully deleted!')

class Ui_addQuestionWindow(object):
    def setupUi(self, addQuestionWindow):
        global style
        addQuestionWindow.setObjectName("addQuestionWindow")
        addQuestionWindow.resize(800, 411)
        addQuestionWindow.setMinimumSize(QtCore.QSize(800, 411))
        addQuestionWindow.setMaximumSize(QtCore.QSize(800, 411))
        font = QtGui.QFont()
        font.setPointSize(12)
        addQuestionWindow.setFont(font)
        addQuestionWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        addQuestionWindow.setStyleSheet("background: #282828;")
        addQuestionWindow.setIconSize(QtCore.QSize(80, 70))
        self.centralwidget = QtWidgets.QWidget(addQuestionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 0, 800, 91))
        font.setFamily("MS Gothic")
        font.setPointSize(40)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setStyleSheet("color: white;")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(False)
        self.title.setOpenExternalLinks(False)
        self.title.setObjectName("title")
        self.addQuestionsButton = QtWidgets.QPushButton(self.centralwidget)
        self.addQuestionsButton.setGeometry(QtCore.QRect(250, 360, 301, 41))
        font.setPointSize(25)
        self.addQuestionsButton.setFont(font)
        self.addQuestionsButton.setStyleSheet("color: white;")
        self.addQuestionsButton.setAutoDefault(False)
        self.addQuestionsButton.setDefault(False)
        self.addQuestionsButton.setFlat(False)
        self.addQuestionsButton.setObjectName("addQuestionsButton")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 120, 781, 230))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.quizTitle = QtWidgets.QLabel(self.formLayoutWidget)
        font.setPointSize(17)
        self.quizTitle.setFont(font)
        self.quizTitle.setStyleSheet("color: white;")
        self.quizTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.quizTitle.setObjectName("quizTitle")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.quizTitle)
        self.quizTitleEntry = QtWidgets.QLineEdit(self.formLayoutWidget)
        font.setPointSize(20)
        self.quizTitleEntry.setFont(font)
        self.quizTitleEntry.setStyleSheet(style)
        self.quizTitleEntry.setText("")
        self.quizTitleEntry.setFrame(False)
        self.quizTitleEntry.setAlignment(QtCore.Qt.AlignCenter)
        self.quizTitleEntry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.quizTitleEntry.setObjectName("quizTitleEntry")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.quizTitleEntry)
        self.question1title = QtWidgets.QLabel(self.formLayoutWidget)
        font.setPointSize(17)
        self.question1title.setFont(font)
        self.question1title.setStyleSheet("color: white;")
        self.question1title.setAlignment(QtCore.Qt.AlignCenter)
        self.question1title.setObjectName("question1title")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.question1title)
        self.question2title = QtWidgets.QLabel(self.formLayoutWidget)
        self.question2title.setFont(font)
        self.question2title.setStyleSheet("color: white;")
        self.question2title.setAlignment(QtCore.Qt.AlignCenter)
        self.question2title.setObjectName("question2title")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.question2title)
        self.question3title = QtWidgets.QLabel(self.formLayoutWidget)
        self.question3title.setFont(font)
        self.question3title.setStyleSheet("color: white;")
        self.question3title.setAlignment(QtCore.Qt.AlignCenter)
        self.question3title.setObjectName("question3title")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.question3title)
        self.question4title = QtWidgets.QLabel(self.formLayoutWidget)
        self.question4title.setFont(font)
        self.question4title.setStyleSheet("color: white;")
        self.question4title.setAlignment(QtCore.Qt.AlignCenter)
        self.question4title.setObjectName("question4title")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.question4title)
        self.question5title = QtWidgets.QLabel(self.formLayoutWidget)
        self.question5title.setFont(font)
        self.question5title.setStyleSheet("color: white;")
        self.question5title.setAlignment(QtCore.Qt.AlignCenter)
        self.question5title.setObjectName("question5title")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.question5title)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.question1entry = QtWidgets.QLineEdit(self.formLayoutWidget)
        font.setPointSize(19)
        self.question1entry.setFont(font)
        self.question1entry.setStyleSheet(style)
        self.question1entry.setText("")
        self.question1entry.setFrame(False)
        self.question1entry.setAlignment(QtCore.Qt.AlignCenter)
        self.question1entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.question1entry.setObjectName("question1entry")
        self.horizontalLayout.addWidget(self.question1entry)
        self.answer1entry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.answer1entry.setFont(font)
        self.answer1entry.setStyleSheet(style)
        self.answer1entry.setText("")
        self.answer1entry.setFrame(False)
        self.answer1entry.setAlignment(QtCore.Qt.AlignCenter)
        self.answer1entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.answer1entry.setObjectName("answer1entry")
        self.horizontalLayout.addWidget(self.answer1entry)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.question2entry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.question2entry.setFont(font)
        self.question2entry.setStyleSheet(style)
        self.question2entry.setText("")
        self.question2entry.setFrame(False)
        self.question2entry.setAlignment(QtCore.Qt.AlignCenter)
        self.question2entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.question2entry.setObjectName("question2entry")
        self.horizontalLayout_2.addWidget(self.question2entry)
        self.answer2entry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.answer2entry.setFont(font)
        self.answer2entry.setStyleSheet(style)
        self.answer2entry.setText("")
        self.answer2entry.setFrame(False)
        self.answer2entry.setAlignment(QtCore.Qt.AlignCenter)
        self.answer2entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.answer2entry.setObjectName("answer2entry")
        self.horizontalLayout_2.addWidget(self.answer2entry)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.question3entry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.question3entry.setFont(font)
        self.question3entry.setStyleSheet(style)
        self.question3entry.setText("")
        self.question3entry.setFrame(False)
        self.question3entry.setAlignment(QtCore.Qt.AlignCenter)
        self.question3entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.question3entry.setObjectName("question3entry")
        self.horizontalLayout_3.addWidget(self.question3entry)
        self.answer3entry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.answer3entry.setFont(font)
        self.answer3entry.setStyleSheet(style)
        self.answer3entry.setText("")
        self.answer3entry.setFrame(False)
        self.answer3entry.setAlignment(QtCore.Qt.AlignCenter)
        self.answer3entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.answer3entry.setObjectName("answer3entry")
        self.horizontalLayout_3.addWidget(self.answer3entry)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.question5entry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.question5entry.setFont(font)
        self.question5entry.setStyleSheet(style)
        self.question5entry.setText("")
        self.question5entry.setFrame(False)
        self.question5entry.setAlignment(QtCore.Qt.AlignCenter)
        self.question5entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.question5entry.setObjectName("question5entry")
        self.horizontalLayout_4.addWidget(self.question5entry)
        self.answer5entry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.answer5entry.setFont(font)
        self.answer5entry.setStyleSheet(style)
        self.answer5entry.setText("")
        self.answer5entry.setFrame(False)
        self.answer5entry.setAlignment(QtCore.Qt.AlignCenter)
        self.answer5entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.answer5entry.setObjectName("answer5entry")
        self.horizontalLayout_4.addWidget(self.answer5entry)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.question4entry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.question4entry.setFont(font)
        self.question4entry.setStyleSheet(style)
        self.question4entry.setText("")
        self.question4entry.setFrame(False)
        self.question4entry.setAlignment(QtCore.Qt.AlignCenter)
        self.question4entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.question4entry.setObjectName("question4entry")
        self.horizontalLayout_5.addWidget(self.question4entry)
        self.answer4entry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.answer4entry.setFont(font)
        self.answer4entry.setStyleSheet(style)
        self.answer4entry.setText("")
        self.answer4entry.setFrame(False)
        self.answer4entry.setAlignment(QtCore.Qt.AlignCenter)
        self.answer4entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.answer4entry.setObjectName("answer4entry")
        self.horizontalLayout_5.addWidget(self.answer4entry)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.quitButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitButton.setGeometry(QtCore.QRect(650, 370, 141, 31))
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.quitButton.setFont(font)
        self.quitButton.setStyleSheet("color: white;")
        self.quitButton.setAutoDefault(False)
        self.quitButton.setDefault(False)
        self.quitButton.setFlat(False)
        self.quitButton.setObjectName("quitButton")
        addQuestionWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(addQuestionWindow)
        QtCore.QMetaObject.connectSlotsByName(addQuestionWindow)
        self.quitButton.clicked.connect(self.quitMethod)
        self.entries = [self.quizTitleEntry, self.question1entry, self.answer1entry, self.question2entry, self.answer2entry, self.question3entry, self.answer3entry, self.question4entry, self.answer4entry, self.question5entry, self.answer5entry]
        self.addQuestionsButton.clicked.connect(self.addQuizMethod)

    def retranslateUi(self, addQuestionWindow):
        _translate = QtCore.QCoreApplication.translate
        addQuestionWindow.setWindowTitle(_translate("addQuestionWindow", "MainWindow"))
        self.title.setText(_translate("addQuestionWindow", "Add A Quiz"))
        self.addQuestionsButton.setText(_translate("addQuestionWindow", "Add Questions"))
        self.quizTitle.setText(_translate("addQuestionWindow", "QuizeTitle:"))
        self.quizTitleEntry.setPlaceholderText(_translate("addQuestionWindow", "Enter Quiz Title Here"))
        self.question1title.setText(_translate("addQuestionWindow", "Question1:"))
        self.question2title.setText(_translate("addQuestionWindow", "Question2:"))
        self.question3title.setText(_translate("addQuestionWindow", "Question3:"))
        self.question4title.setText(_translate("addQuestionWindow", "Question4:"))
        self.question5title.setText(_translate("addQuestionWindow", "Question5:"))
        self.question1entry.setPlaceholderText(_translate("addQuestionWindow", "Enter Question Here"))
        self.answer1entry.setPlaceholderText(_translate("addQuestionWindow", "Enter Answer Here"))
        self.question2entry.setPlaceholderText(_translate("addQuestionWindow", "Enter Question Here"))
        self.answer2entry.setPlaceholderText(_translate("addQuestionWindow", "Enter Answer Here"))
        self.question3entry.setPlaceholderText(_translate("addQuestionWindow", "Enter Question Here"))
        self.answer3entry.setPlaceholderText(_translate("addQuestionWindow", "Enter Answer Here"))
        self.question5entry.setPlaceholderText(_translate("addQuestionWindow", "Enter Question Here"))
        self.answer5entry.setPlaceholderText(_translate("addQuestionWindow", "Enter Answer Here"))
        self.question4entry.setPlaceholderText(_translate("addQuestionWindow", "Enter Question Here"))
        self.answer4entry.setPlaceholderText(_translate("addQuestionWindow", "Enter Answer Here"))
        self.quitButton.setText(_translate("addQuestionWindow", "Cancel"))

    def quitMethod(self):
        QtWidgets.qApp.quit()

    def addQuizMethod(self):
        quizNames = databaseAccess('SELECT QuizName FROM tblQuiz')
        recordInformation = []
        valid = True
        for items in self.entries:
            recordInformation.append(items.text())
            if items.text() == '':
                valid = False
        if valid == False:
            messageBox('Input Error', 'Please fill in all the entry boxes before trying to add the quiz')
        valid2 = True 
        for titles in quizNames:
            if titles[0] == recordInformation[0]:
                valid2 = False
        if valid == True:
            if valid2 == False:
                messageBox('Duplicate name error', 'Sorry a quiz with that title is already logged in the program')
            else:
                databaseAccess(('INSERT INTO tblQuiz (QuizName, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, QuestionFive, QuestionOneAnswer, QuestionTwoAnswer, QuestionThreeAnswer, QuestionFourAnswer, QuestionFiveAnswer) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'), (recordInformation[0], recordInformation[1], recordInformation[3], recordInformation[5], recordInformation[7], recordInformation[9], recordInformation[2], recordInformation[4], recordInformation[6], recordInformation[8], recordInformation[10]))
                messageBox('Success', f'{recordInformation[0]} has been succesfully added to the quiz list!')
                QtWidgets.qApp.quit()

class Ui_editQuizWindow(object):
    def setupUi(self, editQuizWindow):
        global style
        editQuizWindow.setObjectName("editQuizWindow")
        editQuizWindow.resize(800, 411)
        editQuizWindow.setMinimumSize(QtCore.QSize(800, 411))
        editQuizWindow.setMaximumSize(QtCore.QSize(800, 411))
        font = QtGui.QFont()
        font.setPointSize(12)
        editQuizWindow.setFont(font)
        editQuizWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        editQuizWindow.setStyleSheet("background: #282828;")
        editQuizWindow.setIconSize(QtCore.QSize(80, 70))
        self.centralwidget = QtWidgets.QWidget(editQuizWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 0, 800, 91))
        font.setFamily("MS Gothic")
        font.setPointSize(40)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setStyleSheet("color: white;")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(False)
        self.title.setOpenExternalLinks(False)
        self.title.setObjectName("title")
        self.addQuestionsButton = QtWidgets.QPushButton(self.centralwidget)
        self.addQuestionsButton.setGeometry(QtCore.QRect(250, 360, 301, 41))
        font.setPointSize(25)
        self.addQuestionsButton.setFont(font)
        self.addQuestionsButton.setStyleSheet("color: white;")
        self.addQuestionsButton.setAutoDefault(False)
        self.addQuestionsButton.setDefault(False)
        self.addQuestionsButton.setFlat(False)
        self.addQuestionsButton.setObjectName("addQuestionsButton")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 120, 781, 230))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.quizTitle = QtWidgets.QLabel(self.formLayoutWidget)
        font.setPointSize(17)
        self.quizTitle.setFont(font)
        self.quizTitle.setStyleSheet("color: white;")
        self.quizTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.quizTitle.setObjectName("quizTitle")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.quizTitle)
        self.quizTitleEntry = QtWidgets.QLineEdit(self.formLayoutWidget)
        font.setPointSize(20)
        self.quizTitleEntry.setFont(font)
        self.quizTitleEntry.setStyleSheet(style)
        self.quizTitleEntry.setText("")
        self.quizTitleEntry.setFrame(False)
        self.quizTitleEntry.setAlignment(QtCore.Qt.AlignCenter)
        self.quizTitleEntry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.quizTitleEntry.setObjectName("quizTitleEntry")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.quizTitleEntry)
        self.question1title = QtWidgets.QLabel(self.formLayoutWidget)
        font.setPointSize(17)
        self.question1title.setFont(font)
        self.question1title.setStyleSheet("color: white;")
        self.question1title.setAlignment(QtCore.Qt.AlignCenter)
        self.question1title.setObjectName("question1title")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.question1title)
        self.question2title = QtWidgets.QLabel(self.formLayoutWidget)
        self.question2title.setFont(font)
        self.question2title.setStyleSheet("color: white;")
        self.question2title.setAlignment(QtCore.Qt.AlignCenter)
        self.question2title.setObjectName("question2title")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.question2title)
        self.question3title = QtWidgets.QLabel(self.formLayoutWidget)
        self.question3title.setFont(font)
        self.question3title.setStyleSheet("color: white;")
        self.question3title.setAlignment(QtCore.Qt.AlignCenter)
        self.question3title.setObjectName("question3title")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.question3title)
        self.question4title = QtWidgets.QLabel(self.formLayoutWidget)
        self.question4title.setFont(font)
        self.question4title.setStyleSheet("color: white;")
        self.question4title.setAlignment(QtCore.Qt.AlignCenter)
        self.question4title.setObjectName("question4title")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.question4title)
        self.question5title = QtWidgets.QLabel(self.formLayoutWidget)
        self.question5title.setFont(font)
        self.question5title.setStyleSheet("color: white;")
        self.question5title.setAlignment(QtCore.Qt.AlignCenter)
        self.question5title.setObjectName("question5title")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.question5title)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.question1entry = QtWidgets.QLineEdit(self.formLayoutWidget)
        font.setPointSize(19)
        self.question1entry.setFont(font)
        self.question1entry.setStyleSheet(style)
        self.question1entry.setText("")
        self.question1entry.setFrame(False)
        self.question1entry.setAlignment(QtCore.Qt.AlignCenter)
        self.question1entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.question1entry.setObjectName("question1entry")
        self.horizontalLayout.addWidget(self.question1entry)
        self.answer1entry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.answer1entry.setFont(font)
        self.answer1entry.setStyleSheet(style)
        self.answer1entry.setText("")
        self.answer1entry.setFrame(False)
        self.answer1entry.setAlignment(QtCore.Qt.AlignCenter)
        self.answer1entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.answer1entry.setObjectName("answer1entry")
        self.horizontalLayout.addWidget(self.answer1entry)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.question2entry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.question2entry.setFont(font)
        self.question2entry.setStyleSheet(style)
        self.question2entry.setText("")
        self.question2entry.setFrame(False)
        self.question2entry.setAlignment(QtCore.Qt.AlignCenter)
        self.question2entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.question2entry.setObjectName("question2entry")
        self.horizontalLayout_2.addWidget(self.question2entry)
        self.answer2entry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.answer2entry.setFont(font)
        self.answer2entry.setStyleSheet(style)
        self.answer2entry.setText("")
        self.answer2entry.setFrame(False)
        self.answer2entry.setAlignment(QtCore.Qt.AlignCenter)
        self.answer2entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.answer2entry.setObjectName("answer2entry")
        self.horizontalLayout_2.addWidget(self.answer2entry)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.question3entry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.question3entry.setFont(font)
        self.question3entry.setStyleSheet(style)
        self.question3entry.setText("")
        self.question3entry.setFrame(False)
        self.question3entry.setAlignment(QtCore.Qt.AlignCenter)
        self.question3entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.question3entry.setObjectName("question3entry")
        self.horizontalLayout_3.addWidget(self.question3entry)
        self.answer3entry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.answer3entry.setFont(font)
        self.answer3entry.setStyleSheet(style)
        self.answer3entry.setText("")
        self.answer3entry.setFrame(False)
        self.answer3entry.setAlignment(QtCore.Qt.AlignCenter)
        self.answer3entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.answer3entry.setObjectName("answer3entry")
        self.horizontalLayout_3.addWidget(self.answer3entry)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.question5entry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.question5entry.setFont(font)
        self.question5entry.setStyleSheet(style)
        self.question5entry.setText("")
        self.question5entry.setFrame(False)
        self.question5entry.setAlignment(QtCore.Qt.AlignCenter)
        self.question5entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.question5entry.setObjectName("question5entry")
        self.horizontalLayout_4.addWidget(self.question5entry)
        self.answer5entry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.answer5entry.setFont(font)
        self.answer5entry.setStyleSheet(style)
        self.answer5entry.setText("")
        self.answer5entry.setFrame(False)
        self.answer5entry.setAlignment(QtCore.Qt.AlignCenter)
        self.answer5entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.answer5entry.setObjectName("answer5entry")
        self.horizontalLayout_4.addWidget(self.answer5entry)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.question4entry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.question4entry.setFont(font)
        self.question4entry.setStyleSheet(style)
        self.question4entry.setText("")
        self.question4entry.setFrame(False)
        self.question4entry.setAlignment(QtCore.Qt.AlignCenter)
        self.question4entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.question4entry.setObjectName("question4entry")
        self.horizontalLayout_5.addWidget(self.question4entry)
        self.answer4entry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.answer4entry.setFont(font)
        self.answer4entry.setStyleSheet(style)
        self.answer4entry.setText("")
        self.answer4entry.setFrame(False)
        self.answer4entry.setAlignment(QtCore.Qt.AlignCenter)
        self.answer4entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.answer4entry.setObjectName("answer4entry")
        self.horizontalLayout_5.addWidget(self.answer4entry)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.quitButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitButton.setGeometry(QtCore.QRect(650, 370, 141, 31))
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.quitButton.setFont(font)
        self.quitButton.setStyleSheet("color: white;")
        self.quitButton.setAutoDefault(False)
        self.quitButton.setDefault(False)
        self.quitButton.setFlat(False)
        self.quitButton.setObjectName("quitButton")
        editQuizWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(editQuizWindow)
        QtCore.QMetaObject.connectSlotsByName(editQuizWindow)
        self.quitButton.clicked.connect(self.quitMethod)
        global currentUser
        quizTitle = currentUser.method
        self.recordInformation = databaseAccess(('SELECT * FROM tblQuiz WHERE QuizName = ?'), (quizTitle, ))
        self.entries = [self.quizTitleEntry, self.question1entry, self.question2entry, self.question3entry,  self.question4entry, self.question5entry, self.answer1entry, self.answer2entry, self.answer3entry, self.answer4entry, self.answer5entry]
        for i in range(len(self.entries)):
            self.entries[i].setText(self.recordInformation[0][i])
        self.addQuestionsButton.clicked.connect(self.editQuizMethod)

    def retranslateUi(self, editQuizWindow):
        _translate = QtCore.QCoreApplication.translate
        editQuizWindow.setWindowTitle(_translate("editQuizWindow", "MainWindow"))
        self.title.setText(_translate("editQuizWindow", "Edit A Quiz"))
        self.addQuestionsButton.setText(_translate("editQuizWindow", "Save Changes"))
        self.quizTitle.setText(_translate("editQuizWindow", "QuizeTitle:"))
        self.quizTitleEntry.setPlaceholderText(_translate("editQuizWindow", "Enter Quiz Title Here"))
        self.question1title.setText(_translate("editQuizWindow", "Question1:"))
        self.question2title.setText(_translate("editQuizWindow", "Question2:"))
        self.question3title.setText(_translate("editQuizWindow", "Question3:"))
        self.question4title.setText(_translate("editQuizWindow", "Question4:"))
        self.question5title.setText(_translate("editQuizWindow", "Question5:"))
        self.question1entry.setPlaceholderText(_translate("editQuizWindow", "Enter Question Here"))
        self.answer1entry.setPlaceholderText(_translate("editQuizWindow", "Enter Answer Here"))
        self.question2entry.setPlaceholderText(_translate("editQuizWindow", "Enter Question Here"))
        self.answer2entry.setPlaceholderText(_translate("editQuizWindow", "Enter Answer Here"))
        self.question3entry.setPlaceholderText(_translate("editQuizWindow", "Enter Question Here"))
        self.answer3entry.setPlaceholderText(_translate("editQuizWindow", "Enter Answer Here"))
        self.question5entry.setPlaceholderText(_translate("editQuizWindow", "Enter Question Here"))
        self.answer5entry.setPlaceholderText(_translate("editQuizWindow", "Enter Answer Here"))
        self.question4entry.setPlaceholderText(_translate("editQuizWindow", "Enter Question Here"))
        self.answer4entry.setPlaceholderText(_translate("editQuizWindow", "Enter Answer Here"))
        self.quitButton.setText(_translate("editQuizWindow", "Cancel"))

    def quitMethod(self):
        QtWidgets.qApp.quit()

    def editQuizMethod(self):
        valid = True
        changesMade = False
        newData = []
        for i in range(len(self.entries)):
            newData.append(self.entries[i].text())
            if self.entries[i].text() != self.recordInformation[0][i]:
                changesMade = True
        if changesMade == False:
            messageBox('Change Error', 'No changes have been made')
            valid = False
        quizNames = databaseAccess('SELECT QuizName FROM tblQuiz')
        duplicateName = False
        for titles in quizNames:
            if titles[0] == newData[0]:
                if titles[0] != self.recordInformation[0][0]:
                    messageBox('Duplicate Error', 'Sorry you can not rename this quiz to the name of another quiz already stored!')
                    duplicateName = True
                    valid = False 
        filledIn = True
        for items in self.entries:
            if items.text() == '':
                filledIn = False
        if filledIn == False:
            messageBox('Input Error', 'Every box must be filled in before changes can be made')
            valid = False
        if valid == True:
            databaseAccess(('DELETE FROM tblQuiz WHERE QuizName = ?'), (self.recordInformation[0][0], ))
            databaseAccess(('INSERT INTO tblQuiz (QuizName, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, QuestionFive, QuestionOneAnswer, QuestionTwoAnswer, QuestionThreeAnswer, QuestionFourAnswer, QuestionFiveAnswer) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'), (newData[0], newData[1], newData[2], newData[3], newData[4], newData[5], newData[6], newData[7], newData[8], newData[9], newData[10],))
            messageBox('Success', f'Changes to {newData[0]} have successfully been made')
            QtWidgets.qApp.quit()

class Ui_MainMenuWindow(object):
    def setupUi(self, MainMenuWindow):
        MainMenuWindow.setObjectName("MainMenuWindow")
        MainMenuWindow.resize(800, 350)
        MainMenuWindow.setMinimumSize(QtCore.QSize(800, 350))
        MainMenuWindow.setMaximumSize(QtCore.QSize(800, 431))
        MainMenuWindow.setStyleSheet("background: #282828;")
        self.centralwidget = QtWidgets.QWidget(MainMenuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 0, 800, 91))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(40)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setStyleSheet("color: white;")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(False)
        self.title.setOpenExternalLinks(False)
        self.title.setObjectName("title")
        self.quitButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitButton.setGeometry(QtCore.QRect(600, 300, 181, 41))
        font.setPointSize(17)
        self.quitButton.setFont(font)
        self.quitButton.setStyleSheet("color: white;")
        self.quitButton.setAutoDefault(False)
        self.quitButton.setDefault(False)
        self.quitButton.setFlat(False)
        self.quitButton.setObjectName("quitButton")
        self.takeQuizButton = QtWidgets.QPushButton(self.centralwidget)
        self.takeQuizButton.setGeometry(QtCore.QRect(200, 230, 381, 61))
        font.setPointSize(25)
        self.takeQuizButton.setFont(font)
        self.takeQuizButton.setStyleSheet("color: white;")
        self.takeQuizButton.setAutoDefault(False)
        self.takeQuizButton.setDefault(False)
        self.takeQuizButton.setFlat(False)
        self.takeQuizButton.setObjectName("takeQuizButton")
        self.quizComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.quizComboBox.setGeometry(QtCore.QRect(40, 160, 281, 51))
        self.quizComboBox.setObjectName("quizComboBox")
        self.subTitle = QtWidgets.QLabel(self.centralwidget)
        self.subTitle.setGeometry(QtCore.QRect(0, 100, 351, 51))
        font.setPointSize(24)
        self.subTitle.setFont(font)
        self.subTitle.setStyleSheet("color: white;")
        self.subTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.subTitle.setWordWrap(False)
        self.subTitle.setOpenExternalLinks(False)
        self.subTitle.setObjectName("subTitle")
        self.ScoreDisplay = QtWidgets.QLabel(self.centralwidget)
        self.ScoreDisplay.setGeometry(QtCore.QRect(330, 160, 431, 51))
        self.ScoreDisplay.setFont(font)
        self.ScoreDisplay.setStyleSheet("color: white;")
        self.ScoreDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.ScoreDisplay.setWordWrap(False)
        self.ScoreDisplay.setOpenExternalLinks(False)
        self.ScoreDisplay.setObjectName("ScoreDisplay")
        MainMenuWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainMenuWindow)
        QtCore.QMetaObject.connectSlotsByName(MainMenuWindow)
        self.quitButton.clicked.connect(self.quitMethod)
        quizzes = databaseAccess('SELECT QuizName FROM tblQuiz')
        for titles in quizzes:
            self.quizComboBox.addItem(titles[0])
        global currentUser
        oldscore = ''
        for i in range(len(currentUser.scores)):
            if currentUser.scores[i][0] == self.quizComboBox.currentText():
                oldScore = currentUser.scores[i][1]
                break
        if oldScore != '':
            self.ScoreDisplay.setText(f'Your High Score: {oldScore}/5')
        else:
            self.ScoreDisplay.setText(f'No Score Saved')
        self.quitButton.clicked.connect(self.quitMethod)
        self.takeQuizButton.clicked.connect(self.takeQuizMethod)
        self.quizComboBox.currentIndexChanged.connect(self.updateScore)

    def retranslateUi(self, MainMenuWindow):
        _translate = QtCore.QCoreApplication.translate
        MainMenuWindow.setWindowTitle(_translate("MainMenuWindow", "MainWindow"))
        self.title.setText(_translate("MainMenuWindow", "Main Menu"))
        self.quitButton.setText(_translate("MainMenuWindow", "Quit"))
        self.takeQuizButton.setText(_translate("MainMenuWindow", "Take Quiz"))
        self.subTitle.setText(_translate("MainMenuWindow", "Choose A Quiz:"))
        self.ScoreDisplay.setText(_translate("MainMenuWindow", "Your Score on this quiz: -"))

    def updateScore(self):
        global currentUser
        oldscore = ''
        for i in range(len(currentUser.scores)):
            if currentUser.scores[i][0] == self.quizComboBox.currentText():
                oldScore = currentUser.scores[i][1]
                break
        if oldScore != '':
            self.ScoreDisplay.setText(f'Your High Score: {oldScore}/5')
        else:
            self.ScoreDisplay.setText(f'No Score Saved')

    def quitMethod(self):
        QtWidgets.qApp.quit()

    def takeQuizMethod(self):
        selected = self.quizComboBox.currentText() 
        global currentUser
        if selected != '':
            currentUser.method = selected
            QtWidgets.qApp.quit()

class Ui_QuestionEntryWindow(object):
    def setupUi(self, QuestionEntryWindow):
        global style
        QuestionEntryWindow.setObjectName("QuestionEntryWindow")
        QuestionEntryWindow.resize(800, 543)
        QuestionEntryWindow.setMinimumSize(QtCore.QSize(800, 543))
        QuestionEntryWindow.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setPointSize(12)
        QuestionEntryWindow.setFont(font)
        QuestionEntryWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        QuestionEntryWindow.setStyleSheet("background: #282828;")
        QuestionEntryWindow.setIconSize(QtCore.QSize(80, 70))
        self.centralwidget = QtWidgets.QWidget(QuestionEntryWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 0, 800, 91))
        font.setFamily("MS Gothic")
        font.setPointSize(40)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setStyleSheet("color: white;")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(False)
        self.title.setOpenExternalLinks(False)
        self.title.setObjectName("title")
        self.submitAnswersButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitAnswersButton.setGeometry(QtCore.QRect(260, 490, 301, 41))
        font.setPointSize(25)
        self.submitAnswersButton.setFont(font)
        self.submitAnswersButton.setStyleSheet("color: white;")
        self.submitAnswersButton.setAutoDefault(False)
        self.submitAnswersButton.setDefault(False)
        self.submitAnswersButton.setFlat(False)
        self.submitAnswersButton.setObjectName("submitAnswersButton")
        self.question1title = QtWidgets.QLabel(self.centralwidget)
        self.question1title.setGeometry(QtCore.QRect(0, 100, 201, 35))
        font.setPointSize(23)
        self.question1title.setFont(font)
        self.question1title.setStyleSheet("color: white;")
        self.question1title.setAlignment(QtCore.Qt.AlignCenter)
        self.question1title.setObjectName("question1title")
        self.question1entry = QtWidgets.QLineEdit(self.centralwidget)
        self.question1entry.setGeometry(QtCore.QRect(0, 135, 800, 35))
        font.setPointSize(20)
        self.question1entry.setFont(font)
        self.question1entry.setStyleSheet(style)
        self.question1entry.setText("")
        self.question1entry.setFrame(True)
        self.question1entry.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.question1entry.setAlignment(QtCore.Qt.AlignCenter)
        self.question1entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.question1entry.setClearButtonEnabled(False)
        self.question1entry.setObjectName("question1entry")
        self.question1 = QtWidgets.QLabel(self.centralwidget)
        self.question1.setGeometry(QtCore.QRect(200, 100, 591, 35))
        font.setPointSize(17)
        self.question1.setFont(font)
        self.question1.setStyleSheet("color: white;")
        self.question1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.question1.setObjectName("question1")
        self.question2title = QtWidgets.QLabel(self.centralwidget)
        self.question2title.setGeometry(QtCore.QRect(0, 170, 201, 35))
        font.setPointSize(23)
        self.question2title.setFont(font)
        self.question2title.setStyleSheet("color: white;")
        self.question2title.setAlignment(QtCore.Qt.AlignCenter)
        self.question2title.setObjectName("question2title")
        self.question2 = QtWidgets.QLabel(self.centralwidget)
        self.question2.setGeometry(QtCore.QRect(200, 170, 591, 35))
        font.setPointSize(17)
        self.question2.setFont(font)
        self.question2.setStyleSheet("color: white;")
        self.question2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.question2.setObjectName("question2")
        self.question2entry = QtWidgets.QLineEdit(self.centralwidget)
        self.question2entry.setGeometry(QtCore.QRect(0, 210, 800, 35))
        font.setPointSize(20)
        self.question2entry.setFont(font)
        self.question2entry.setStyleSheet(style)
        self.question2entry.setText("")
        self.question2entry.setFrame(True)
        self.question2entry.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.question2entry.setAlignment(QtCore.Qt.AlignCenter)
        self.question2entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.question2entry.setClearButtonEnabled(False)
        self.question2entry.setObjectName("question2entry")
        self.question4title = QtWidgets.QLabel(self.centralwidget)
        self.question4title.setGeometry(QtCore.QRect(0, 320, 201, 35))
        font.setPointSize(23)
        self.question4title.setFont(font)
        self.question4title.setStyleSheet("color: white;")
        self.question4title.setAlignment(QtCore.Qt.AlignCenter)
        self.question4title.setObjectName("question4title")
        self.question3title = QtWidgets.QLabel(self.centralwidget)
        self.question3title.setGeometry(QtCore.QRect(0, 250, 201, 35))
        font.setPointSize(23)
        self.question3title.setFont(font)
        self.question3title.setStyleSheet("color: white;")
        self.question3title.setAlignment(QtCore.Qt.AlignCenter)
        self.question3title.setObjectName("question3title")
        self.question4entry = QtWidgets.QLineEdit(self.centralwidget)
        self.question4entry.setGeometry(QtCore.QRect(0, 360, 800, 35))
        font.setPointSize(20)
        self.question4entry.setFont(font)
        self.question4entry.setStyleSheet(style)
        self.question4entry.setText("")
        self.question4entry.setFrame(True)
        self.question4entry.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.question4entry.setAlignment(QtCore.Qt.AlignCenter)
        self.question4entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.question4entry.setClearButtonEnabled(False)
        self.question4entry.setObjectName("question4entry")
        self.question3 = QtWidgets.QLabel(self.centralwidget)
        self.question3.setGeometry(QtCore.QRect(200, 250, 591, 35))
        font.setPointSize(17)
        self.question3.setFont(font)
        self.question3.setStyleSheet("color: white;")
        self.question3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.question3.setObjectName("question3")
        self.question4 = QtWidgets.QLabel(self.centralwidget)
        self.question4.setGeometry(QtCore.QRect(200, 320, 591, 35))
        font.setPointSize(17)
        self.question4.setFont(font)
        self.question4.setStyleSheet("color: white;")
        self.question4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.question4.setObjectName("question4")
        self.question3entry = QtWidgets.QLineEdit(self.centralwidget)
        self.question3entry.setGeometry(QtCore.QRect(0, 285, 800, 35))
        font.setPointSize(20)
        self.question3entry.setFont(font)
        self.question3entry.setStyleSheet(style)
        self.question3entry.setText("")
        self.question3entry.setFrame(True)
        self.question3entry.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.question3entry.setAlignment(QtCore.Qt.AlignCenter)
        self.question3entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.question3entry.setClearButtonEnabled(False)
        self.question3entry.setObjectName("question3entry")
        self.question5title = QtWidgets.QLabel(self.centralwidget)
        self.question5title.setGeometry(QtCore.QRect(0, 400, 201, 35))
        font.setPointSize(23)
        self.question5title.setFont(font)
        self.question5title.setStyleSheet("color: white;")
        self.question5title.setAlignment(QtCore.Qt.AlignCenter)
        self.question5title.setObjectName("question5title")
        self.question5 = QtWidgets.QLabel(self.centralwidget)
        self.question5.setGeometry(QtCore.QRect(200, 400, 591, 35))
        font.setPointSize(17)
        self.question5.setFont(font)
        self.question5.setStyleSheet("color: white;")
        self.question5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.question5.setObjectName("question5")
        self.question5entry = QtWidgets.QLineEdit(self.centralwidget)
        self.question5entry.setGeometry(QtCore.QRect(0, 440, 800, 35))
        font.setPointSize(20)
        self.question5entry.setFont(font)
        self.question5entry.setStyleSheet(style)
        self.question5entry.setText("")
        self.question5entry.setFrame(True)
        self.question5entry.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.question5entry.setAlignment(QtCore.Qt.AlignCenter)
        self.question5entry.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.question5entry.setClearButtonEnabled(False)
        self.question5entry.setObjectName("question5entry")
        QuestionEntryWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(QuestionEntryWindow)
        QtCore.QMetaObject.connectSlotsByName(QuestionEntryWindow)
        global currentUser
        quizTitle = currentUser.method
        self.recordInformation = databaseAccess(('SELECT * FROM tblQuiz WHERE QuizName = ?'), (quizTitle,))
        self.answers = [self.recordInformation[0][6], self.recordInformation[0][7], self.recordInformation[0][8], self.recordInformation[0][9], self.recordInformation[0][10]]
        self.labels = [self.title, self.question1, self.question2, self.question3,  self.question4, self.question5]
        for i in range(len(self.labels)):
            self.labels[i].setText(self.recordInformation[0][i])
        self.entries = [self.question1entry, self.question2entry, self.question3entry, self.question4entry, self.question5entry]
        self.submitAnswersButton.clicked.connect(self.answerCheck)

    def retranslateUi(self, QuestionEntryWindow):
        _translate = QtCore.QCoreApplication.translate
        QuestionEntryWindow.setWindowTitle(_translate("QuestionEntryWindow", "MainWindow"))
        self.title.setText(_translate("QuestionEntryWindow", "Quiz Title"))
        self.submitAnswersButton.setText(_translate("QuestionEntryWindow", "Submit Answers"))
        self.question1title.setText(_translate("QuestionEntryWindow", "Question 1:"))
        self.question1entry.setPlaceholderText(_translate("QuestionEntryWindow", "Answer to question 1"))
        self.question1.setText(_translate("QuestionEntryWindow", "This is the first question?"))
        self.question2title.setText(_translate("QuestionEntryWindow", "Question 2:"))
        self.question2.setText(_translate("QuestionEntryWindow", "This is the second question?"))
        self.question2entry.setPlaceholderText(_translate("QuestionEntryWindow", "Answer to question 2"))
        self.question4title.setText(_translate("QuestionEntryWindow", "Question 4:"))
        self.question3title.setText(_translate("QuestionEntryWindow", "Question 3:"))
        self.question4entry.setPlaceholderText(_translate("QuestionEntryWindow", "Answer to question 4"))
        self.question3.setText(_translate("QuestionEntryWindow", "This is the third question?"))
        self.question4.setText(_translate("QuestionEntryWindow", "This is the fourth question?"))
        self.question3entry.setPlaceholderText(_translate("QuestionEntryWindow", "Answer to question 3"))
        self.question5title.setText(_translate("QuestionEntryWindow", "Question 5:"))
        self.question5.setText(_translate("QuestionEntryWindow", "This is the fith question ?"))
        self.question5entry.setPlaceholderText(_translate("QuestionEntryWindow", "Answer to question 4"))

    def answerCheck(self):
        global currentUser
        answers = []
        for items in self.entries:
            answers.append(items.text())
        valid = True 
        for items in answers:
            if items == '':
                valid = False
                messageBox('Entry Error', 'Please ensure you have answered all of the questions before trying to submit')
                break 
        if valid == True:
            total = 0
            for index in range(len(answers)):
                if answers[index] == self.answers[index]:
                    total += 1
            extra = ''
            oldscore = ''
            for i in range(len(currentUser.scores)):
                if currentUser.scores[i][0] == currentUser.method:
                    oldScore = currentUser.scores[i][1]
                    break
            if oldScore == '':
                extra = f'!, This score is your first and so will be saved'
            else:
                if oldScore < total:
                    extra = f'!, You beat your old score of {oldScore} this new score will be saved'
                    databaseAccess(('DELETE FROM tblHighScores WHERE QuizName = ? AND Username = ?'), (currentUser.method, currentUser.name))
                    databaseAccess(('INSERT INTO tblHighScores (Username, QuizName, Score) VALUES(?, ?, ?)'), (currentUser.name, currentUser.method, total))
                else:
                    extra = f'!, Your old score was {oldScore} and so no changes will be made'
            messageBox('Entry Confirmed', f'Well done, you scored {total}/5{extra}')
            QtWidgets.qApp.quit()

#the class that creates user objects, this stores the users name and scores, it also stores what the user is currently trying to do
class user:
    def __init__(self, username):
        self.name = username
        self.scores = databaseAccess((f'SELECT QuizName, Score FROM tblHighScores WHERE Username = ?'), (username,))
        self.method = ''

def databaseAccess(query, args=0):
    databaseFile = 'quizDatabase.db'
    databaseConnection = sqlite3.connect(databaseFile)
    cursor = databaseConnection.cursor()
    if args == 0:
        cursor.execute(query)
    else:
        cursor.execute(query, args)
    fetchedData = cursor.fetchall()
    databaseConnection.commit()
    return fetchedData

def messageBox(title, content):
    msgBox = QMessageBox()
    msgBox.setIcon(QMessageBox.Information)
    msgBox.setText(content)
    msgBox.setWindowTitle(title)
    msgBox.exec()

def createAccountWindow():
    app = QtWidgets.QApplication(sys.argv)
    CreateUserWindow = QtWidgets.QMainWindow()
    ui = Ui_CreateUserWindow()
    ui.setupUi(CreateUserWindow)
    CreateUserWindow.show()
    app.exec_()

def logOnWindow():
    app = QtWidgets.QApplication(sys.argv)
    logOnWindow = QtWidgets.QMainWindow()
    ui = Ui_logOnWindow()
    ui.setupUi(logOnWindow)
    logOnWindow.show()
    app.exec_()

def adminMainMenuWindow():
    app = QtWidgets.QApplication(sys.argv)
    adminMainMenuWindow = QtWidgets.QMainWindow()
    ui = Ui_adminMainMenuWindow()
    ui.setupUi(adminMainMenuWindow)
    adminMainMenuWindow.show()
    app.exec_()

def editQuizWindow():
    app = QtWidgets.QApplication(sys.argv)
    editQuizWindow = QtWidgets.QMainWindow()
    ui = Ui_editQuizWindow()
    ui.setupUi(editQuizWindow)
    editQuizWindow.show()
    app.exec_()

def createNewQuizWindow():
    app = QtWidgets.QApplication(sys.argv)
    addQuestionWindow = QtWidgets.QMainWindow()
    ui = Ui_addQuestionWindow()
    ui.setupUi(addQuestionWindow)
    addQuestionWindow.show()
    app.exec_()

def mainMenuWindow():
    app = QtWidgets.QApplication(sys.argv)
    MainMenuWindow = QtWidgets.QMainWindow()
    ui = Ui_MainMenuWindow()
    ui.setupUi(MainMenuWindow)
    MainMenuWindow.show()
    app.exec_()

def answerEntryWindow():
    app = QtWidgets.QApplication(sys.argv)
    QuestionEntryWindow = QtWidgets.QMainWindow()
    ui = Ui_QuestionEntryWindow()
    ui.setupUi(QuestionEntryWindow)
    QuestionEntryWindow.show()
    app.exec_()
    
def main():
    global currentUser
    while True:
        logOnWindow()
        if currentUser == 'createNew':
            createAccountWindow()
        else:
            break
    if currentUser != '':
        if currentUser.name == 'Admin':
            while True:
                currentUser.method = ''
                adminMainMenuWindow()
                if currentUser.method == 'createNewQuiz':
                    createNewQuizWindow()
                elif currentUser.method == 'quit':
                    break
                elif currentUser.method != '':
                    editQuizWindow()
                else:
                    break
        else:
            while True:
                currentUser.method = 'quit'
                mainMenuWindow()
                if currentUser.method == 'quit':
                    break
                else:
                    answerEntryWindow()

if __name__ == '__main__':
    main()

